allpieces = {
  3:"Straight",
  42:"Straight short",
  1:"Start",
  2:"Finish",
  
  4:"Flat small",
  6:"Flat medium",
  8:"Flat large",
  59:"Left slope medium",
  58:"Right slope medium",
  54:"Left slope large",
  53:"Right slope large",
  26:"T cross",
  27:"+ cross",
  28:"Y cross",
  
  65:"Small left",
  64:"Small right",
  67:"Medium left",
  66:"Medium right",
  69:"Big left",
  68:"Big right",
  
  17:"Climb 3-1",
  18:"Climb 6-2",
  22:"Climb 9-3",
  23:"Slope start",
  24:"Slope",
  25:"Slope end",
  76:"Flat to slope left",
  26:"Flat to slope right",
  
  13:"Horizontal",
  70:"Horizontal short",
  12:"Vertical",
  71:"Vertical short 1",
  72:"Vertical short 2",
  15:"Slope start",
  14:"Slope",
  16:"Slope end",
  9:"Curve 1",
  10:"Curve 2",
  11:"Curve 3",
  
  32:"Side",
  74:"Side short",
  29:"Middle",
  73:"Middle short",
  30:"Corner",
  31:"Corner2",
  33:"Slope start border left",
  36:"Slope start no border",
  39:"Slope start border right",
  34:"Slope border left",
  37:"Slope no border",
  40:"Slope border right",
  35:"Slope end border left",
  38:"Slope end no border",
  41:"Slope end border right",

  49:"Tilted",
  61:"Transition left",
  60:"Transition right",
  63:"Transition turn left",
  62:"Transition turn right",
  57:"Turn medium",
  52:"Turn large",
  80:"Left slope down",
  79:"Right slope down",
  78:"Left slope up",
  77:"Right slope up",
  
  44:"Loop left",
  19:"Loop right",
  46:"Loop wide left",
  45:"Loop wide right",
  
  91:"Horizontal",
  92:"Horizontal short",
  93:"Vertical",
  94:"Vertical short",
  95:"Horizontal",
  96:"Vertical 1",
  97:"Vertical 2",
  
  98:"Ground block",
  101:"Trees",
  103:"Tree",
  
  81:"Horizontal",
  82:"Horizontal short",
  83:"Vertical",
  84:"Vertical short",
  90:"Transition",
  85:"Horizontal curve",
  86:"Vertical curve 1",
  87:"Vertical curve 2",
  88:"Cross horizontal",
  89:"Cross vertical",
  43:"Grass ramp",
  20:"Arrows left",
  21:"Arrows right",
  48:"Arrows down",
  47:"Arrows up"
}
